services:
  redis:
    image: redis:latest
    container_name: chai-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    
   
   mongodb:
    image: mongo:latest
    container_name: chai-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: chai_mongodb

volumes:
  redis-data: 
  mongo-data: